version: '3.8'

services:
  game-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NUGET_AUTH_TOKEN: ${NUGET_TOKEN}
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
      # --- CONFIGURATION OPENTELEMETRY (Fournie par tes OPS) ---
      
      # Le nom qui apparaitra dans les logs
      - OTEL_SERVICE_NAME=dungeoncrawler-game-service
      
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf

      # Active tout (Logs, Traces, Metrics)
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      
      # Tags pour filtrer (ex: prod vs dev)
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=dev,service.version=1.0.0

  # (Optionnel) Si tu veux tester en local sans le cluster des OPS,
  # tu peux lancer une version "light" de la stack d'observabilit√© :
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true